# ******* WARNING - AUTO GENERATED CODE - DO NOT EDIT *******

module VimSdk
  module VmomiSupport

    add_version("vmodl.query.version.version1", "", "", false, "vim25")
    add_version("vmodl.query.version.version2", "", "", false, "vim25")
    add_version("vmodl.query.version.version3", "", "", false, "vim25")
    add_version("vmodl.query.version.version4", "", "", false, "vim25")
    add_version("vmodl.version.version2", "", "", false, "vim25")
    add_version("vmodl.version.version1", "", "", false, "vim25")
    add_version("vmodl.version.version0", "", "", false, "vim25")
    add_version_parent("vmodl.query.version.version1", "vmodl.query.version.version1")
    add_version_parent("vmodl.query.version.version1", "vmodl.version.version0")
    add_version_parent("vmodl.query.version.version2", "vmodl.query.version.version1")
    add_version_parent("vmodl.query.version.version2", "vmodl.query.version.version2")
    add_version_parent("vmodl.query.version.version2", "vmodl.version.version1")
    add_version_parent("vmodl.query.version.version2", "vmodl.version.version0")
    add_version_parent("vmodl.query.version.version3", "vmodl.query.version.version1")
    add_version_parent("vmodl.query.version.version3", "vmodl.query.version.version2")
    add_version_parent("vmodl.query.version.version3", "vmodl.query.version.version3")
    add_version_parent("vmodl.query.version.version3", "vmodl.version.version1")
    add_version_parent("vmodl.query.version.version3", "vmodl.version.version0")
    add_version_parent("vmodl.query.version.version4", "vmodl.query.version.version1")
    add_version_parent("vmodl.query.version.version4", "vmodl.query.version.version2")
    add_version_parent("vmodl.query.version.version4", "vmodl.query.version.version3")
    add_version_parent("vmodl.query.version.version4", "vmodl.query.version.version4")
    add_version_parent("vmodl.query.version.version4", "vmodl.version.version2")
    add_version_parent("vmodl.query.version.version4", "vmodl.version.version1")
    add_version_parent("vmodl.query.version.version4", "vmodl.version.version0")
    add_version_parent("vmodl.version.version2", "vmodl.version.version2")
    add_version_parent("vmodl.version.version2", "vmodl.version.version1")
    add_version_parent("vmodl.version.version2", "vmodl.version.version0")
    add_version_parent("vmodl.version.version1", "vmodl.version.version1")
    add_version_parent("vmodl.version.version1", "vmodl.version.version0")
    add_version_parent("vmodl.version.version0", "vmodl.version.version0")
    newestVersions.add("vmodl.query.version.version4")
    stableVersions.add("vmodl.query.version.version4")
    publicVersions.add("vmodl.query.version.version4")
    oldestVersions.add("vmodl.query.version.version1")
    create_data_type("vmodl.query.InvalidCollectorVersion", "InvalidCollectorVersion", "vmodl.MethodFault", "vmodl.query.version.version1", nil)
    create_data_type("vmodl.query.InvalidProperty", "InvalidProperty", "vmodl.MethodFault", "vmodl.query.version.version1", [["name", "vmodl.PropertyPath", "vmodl.query.version.version1"]])
    create_managed_type("vmodl.query.PropertyCollector", "PropertyCollector", "vmodl.ManagedObject", "vmodl.query.version.version1", [["filter", "vmodl.query.PropertyCollector.Filter[]", "vmodl.query.version.version1", {:optional => true}, "System.View"]], [["createFilter", "CreateFilter", "vmodl.query.version.version1", [["spec", "vmodl.query.PropertyCollector.FilterSpec", "vmodl.query.version.version1", {}, nil], ["partialUpdates", "boolean", "vmodl.query.version.version1", {}, nil]], [{}, "vmodl.query.PropertyCollector.Filter", "vmodl.query.PropertyCollector.Filter"], "System.View", ["vmodl.query.InvalidProperty"]], ["retrieveContents", "RetrieveProperties", "vmodl.query.version.version1", [["specSet", "vmodl.query.PropertyCollector.FilterSpec[]", "vmodl.query.version.version1", {}, nil]], [{:optional => true}, "vmodl.query.PropertyCollector.ObjectContent[]", "vmodl.query.PropertyCollector.ObjectContent[]"], "System.Anonymous", ["vmodl.query.InvalidProperty"]], ["checkForUpdates", "CheckForUpdates", "vmodl.query.version.version1", [["version", "string", "vmodl.query.version.version1", {:optional => true}, nil]], [{:optional => true}, "vmodl.query.PropertyCollector.UpdateSet", "vmodl.query.PropertyCollector.UpdateSet"], "System.View", ["vmodl.query.InvalidCollectorVersion"]], ["waitForUpdates", "WaitForUpdates", "vmodl.query.version.version1", [["version", "string", "vmodl.query.version.version1", {:optional => true}, nil]], [{}, "vmodl.query.PropertyCollector.UpdateSet", "vmodl.query.PropertyCollector.UpdateSet"], "System.View", ["vmodl.query.InvalidCollectorVersion"]], ["cancelWaitForUpdates", "CancelWaitForUpdates", "vmodl.query.version.version1", [], [{}, "void", "void"], "System.View", nil], ["waitForUpdatesEx", "WaitForUpdatesEx", "vmodl.query.version.version3", [["version", "string", "vmodl.query.version.version3", {:optional => true}, nil], ["options", "vmodl.query.PropertyCollector.WaitOptions", "vmodl.query.version.version3", {:optional => true}, nil]], [{:optional => true}, "vmodl.query.PropertyCollector.UpdateSet", "vmodl.query.PropertyCollector.UpdateSet"], "System.View", ["vmodl.query.InvalidCollectorVersion"]], ["retrievePropertiesEx", "RetrievePropertiesEx", "vmodl.query.version.version3", [["specSet", "vmodl.query.PropertyCollector.FilterSpec[]", "vmodl.query.version.version3", {}, nil], ["options", "vmodl.query.PropertyCollector.RetrieveOptions", "vmodl.query.version.version3", {}, nil]], [{:optional => true}, "vmodl.query.PropertyCollector.RetrieveResult", "vmodl.query.PropertyCollector.RetrieveResult"], "System.Anonymous", ["vmodl.query.InvalidProperty"]], ["continueRetrievePropertiesEx", "ContinueRetrievePropertiesEx", "vmodl.query.version.version3", [["token", "string", "vmodl.query.version.version3", {}, nil]], [{}, "vmodl.query.PropertyCollector.RetrieveResult", "vmodl.query.PropertyCollector.RetrieveResult"], "System.Anonymous", ["vmodl.query.InvalidProperty"]], ["cancelRetrievePropertiesEx", "CancelRetrievePropertiesEx", "vmodl.query.version.version3", [["token", "string", "vmodl.query.version.version3", {}, nil]], [{}, "void", "void"], "System.Anonymous", ["vmodl.query.InvalidProperty"]], ["createPropertyCollector", "CreatePropertyCollector", "vmodl.query.version.version3", [], [{}, "vmodl.query.PropertyCollector", "vmodl.query.PropertyCollector"], "System.View", nil], ["destroy", "DestroyPropertyCollector", "vmodl.query.version.version3", [], [{}, "void", "void"], "System.View", nil]])
    create_data_type("vmodl.query.PropertyCollector.FilterSpec", "PropertyFilterSpec", "vmodl.DynamicData", "vmodl.query.version.version1", [["propSet", "vmodl.query.PropertyCollector.PropertySpec[]", "vmodl.query.version.version1"], ["objectSet", "vmodl.query.PropertyCollector.ObjectSpec[]", "vmodl.query.version.version1"], ["reportMissingObjectsInResults", "boolean", "vmodl.query.version.version3", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.PropertySpec", "PropertySpec", "vmodl.DynamicData", "vmodl.query.version.version1", [["type", "vmodl.TypeName", "vmodl.query.version.version1"], ["all", "boolean", "vmodl.query.version.version1", {:optional => true}], ["pathSet", "vmodl.PropertyPath[]", "vmodl.query.version.version1", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.ObjectSpec", "ObjectSpec", "vmodl.DynamicData", "vmodl.query.version.version1", [["obj", "vmodl.ManagedObject", "vmodl.query.version.version1"], ["skip", "boolean", "vmodl.query.version.version1", {:optional => true}], ["selectSet", "vmodl.query.PropertyCollector.SelectionSpec[]", "vmodl.query.version.version1", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.SelectionSpec", "SelectionSpec", "vmodl.DynamicData", "vmodl.query.version.version1", [["name", "string", "vmodl.query.version.version1", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.TraversalSpec", "TraversalSpec", "vmodl.query.PropertyCollector.SelectionSpec", "vmodl.query.version.version1", [["type", "vmodl.TypeName", "vmodl.query.version.version1"], ["path", "vmodl.PropertyPath", "vmodl.query.version.version1"], ["skip", "boolean", "vmodl.query.version.version1", {:optional => true}], ["selectSet", "vmodl.query.PropertyCollector.SelectionSpec[]", "vmodl.query.version.version1", {:optional => true}]])
    create_managed_type("vmodl.query.PropertyCollector.Filter", "PropertyFilter", "vmodl.ManagedObject", "vmodl.query.version.version1", [["spec", "vmodl.query.PropertyCollector.FilterSpec", "vmodl.query.version.version1", {}, nil], ["partialUpdates", "boolean", "vmodl.query.version.version1", {}, nil]], [["destroy", "DestroyPropertyFilter", "vmodl.query.version.version1", [], [{}, "void", "void"], nil, nil]])
    create_data_type("vmodl.query.PropertyCollector.ObjectContent", "ObjectContent", "vmodl.DynamicData", "vmodl.query.version.version1", [["obj", "vmodl.ManagedObject", "vmodl.query.version.version1"], ["propSet", "vmodl.DynamicProperty[]", "vmodl.query.version.version1", {:optional => true}], ["missingSet", "vmodl.query.PropertyCollector.MissingProperty[]", "vmodl.query.version.version1", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.UpdateSet", "UpdateSet", "vmodl.DynamicData", "vmodl.query.version.version1", [["version", "string", "vmodl.query.version.version1"], ["filterSet", "vmodl.query.PropertyCollector.FilterUpdate[]", "vmodl.query.version.version1", {:optional => true}], ["truncated", "boolean", "vmodl.query.version.version3", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.FilterUpdate", "PropertyFilterUpdate", "vmodl.DynamicData", "vmodl.query.version.version1", [["filter", "vmodl.query.PropertyCollector.Filter", "vmodl.query.version.version1"], ["objectSet", "vmodl.query.PropertyCollector.ObjectUpdate[]", "vmodl.query.version.version1", {:optional => true}], ["missingSet", "vmodl.query.PropertyCollector.MissingObject[]", "vmodl.query.version.version1", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.ObjectUpdate", "ObjectUpdate", "vmodl.DynamicData", "vmodl.query.version.version1", [["kind", "vmodl.query.PropertyCollector.ObjectUpdate.Kind", "vmodl.query.version.version1"], ["obj", "vmodl.ManagedObject", "vmodl.query.version.version1"], ["changeSet", "vmodl.query.PropertyCollector.Change[]", "vmodl.query.version.version1", {:optional => true}], ["missingSet", "vmodl.query.PropertyCollector.MissingProperty[]", "vmodl.query.version.version1", {:optional => true}]])
    create_enum_type("vmodl.query.PropertyCollector.ObjectUpdate.Kind", "ObjectUpdateKind", "vmodl.query.version.version1", ["modify", "enter", "leave"])
    create_data_type("vmodl.query.PropertyCollector.Change", "PropertyChange", "vmodl.DynamicData", "vmodl.query.version.version1", [["name", "vmodl.PropertyPath", "vmodl.query.version.version1"], ["op", "vmodl.query.PropertyCollector.Change.Op", "vmodl.query.version.version1"], ["val", "anyType", "vmodl.query.version.version1", {:optional => true}]])
    create_enum_type("vmodl.query.PropertyCollector.Change.Op", "PropertyChangeOp", "vmodl.query.version.version1", ["add", "remove", "assign", "indirectRemove"])
    create_data_type("vmodl.query.PropertyCollector.MissingProperty", "MissingProperty", "vmodl.DynamicData", "vmodl.query.version.version1", [["path", "vmodl.PropertyPath", "vmodl.query.version.version1"], ["fault", "vmodl.MethodFault", "vmodl.query.version.version1"]])
    create_data_type("vmodl.query.PropertyCollector.MissingObject", "MissingObject", "vmodl.DynamicData", "vmodl.query.version.version1", [["obj", "vmodl.ManagedObject", "vmodl.query.version.version1"], ["fault", "vmodl.MethodFault", "vmodl.query.version.version1"]])
    create_data_type("vmodl.query.PropertyCollector.WaitOptions", "WaitOptions", "vmodl.DynamicData", "vmodl.query.version.version3", [["maxWaitSeconds", "int", "vmodl.query.version.version3", {:optional => true}], ["maxObjectUpdates", "int", "vmodl.query.version.version3", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.RetrieveOptions", "RetrieveOptions", "vmodl.DynamicData", "vmodl.query.version.version3", [["maxObjects", "int", "vmodl.query.version.version3", {:optional => true}]])
    create_data_type("vmodl.query.PropertyCollector.RetrieveResult", "RetrieveResult", "vmodl.DynamicData", "vmodl.query.version.version3", [["token", "string", "vmodl.query.version.version3", {:optional => true}], ["objects", "vmodl.query.PropertyCollector.ObjectContent[]", "vmodl.query.version.version3"]])
  end
end

